name: automate frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: echo "building......"
    

    - name: Deploy to Ubuntu 22.04
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST1 }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY1 }}
        port: 22
        script: |
          npm install npm@9 -g
          git clone https://github.com/louislam/uptime-kuma.git
          cd uptime-kuma
          node server/server.js
          npm install pm2 -g && pm2 install pm2-logrotate
          pm2 start server/server.js --name uptime-kuma
