name: Node.js

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST1 }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY1 }}
          port: 22
          script: |
            sudo apt update
            sudo apt install -y nodejs npm
            npm install -g pm2
            cd /github/workspace
            rm -rf uptime-kuma
            git clone https://github.com/louislam/uptime-kuma.git
            cd uptime-kuma
            npm install
            pm2 start server/server.js --name uptime-kuma
